[package]
name = "startpay-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
hmac = "0.12"
sha-1 = "0.10"
base64 = "0.22"
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
